portalprofesores/WebUI/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Seleccion.Helpers;
using DataAccess;
using WebUI.Helpers;
using Logger;
using System.Configuration;
using System.Net;
using System.IO;
using WebUI.Classes;

namespace WebUI.Controllers
{
    public class ReporteController : Controller
    {
        public ActionResult Index()
        {
            if (SimpleSecurity.HaySessionActiva())
            {
                try
                {
                    var p = ProfesorHelper.ObtenerProfesor();
                    //ViewBag.Areas = new AreaRepository().RetrieveAll();

                    return View(p);
                }
                catch (Exception ex)
                {
                    EventLogger logger = new EventLogger("SiteProfesores");
                    string information = "";
                    information += "Ubicacion: Main/GenerarReporte \n";
                    information += "Id Profesor:" + WrapperSession.ObtenerInstancia().Id + "\n";
                    information += "Error: " + ex.Message + "\n";
                    information += "Inner Exception: " + ex.InnerException + "\n";
                    if (ex.InnerException != null)
                        information += "Inner Exception Messaje: " + ex.InnerException.Message + "\n";
                    information += "Stack Trace: " + ex.StackTrace + "\n";

                    logger.Error(information);
                }
                return RedirectToAction("Login", "Main");
            }
            else
            {
                TempData["Timeout"] = true;
                return RedirectToAction("Login", "Main");
            }
        }

        //public void Exportar(string indiceReporte, ParametrosReporte parametros)
        //{
        //    try
        //    {
        //        if (String.IsNullOrEmpty(parametros.Termino) && String.IsNullOrEmpty(parametros.Ano))
        //        {
        //            var periodoActual = new PeriodoRepository().RetrieveAll().FirstOrDefault();
        //            parametros.Termino = periodoActual.Termino;
        //            parametros.Ano = periodoActual.Ano;
        //        }
        //        var result = CargarInformacion(indiceReporte, parametros);
        //        GenerarReporte(result.url, result.titulo, result.parametros);
        //    }
        //    catch (Exception ex)
        //    {
        //        EventLogger logger = new EventLogger("SiteProfesores");
        //        string information = "";
        //        information += "Ubicacion: Main/GenerarReporte \n";
        //        information += "Id Profesor:" + WrapperSession.ObtenerInstancia().Id + "\n";
        //        information += "Error: " + ex.Message + "\n";
        //        information += "Inner Exception: " + ex.InnerException + "\n";
        //        if (ex.InnerException != null)
        //            information += "Inner Exception Messaje: " + ex.InnerException.Message + "\n";
        //        information += "Stack Trace: " + ex.StackTrace + "\n";

        //        logger.Error(information);
        //    }
        //}

        //[HttpPost]
        //public ActionResult ObtenerCarreras(int idEstudiante)
        //{
        //    var carreras = new CarrerasRepository().ObtenerCarreras(idEstudiante);
        //    return Json(new { carreras = carreras.Select(m => new { m.Codigo, m.Descripcion }) });
        //}

        //#region Metodos Privados
        //private dynamic CargarInformacion(string indiceReporte, ParametrosReporte parametros)
        //{
        //    var dataReporte = ReportCenterConfiguration.Instance.Reports[indiceReporte];
        //    var args = new Dictionary<string, string>();
        //    var periodoActual = new PeriodoRepository().RetrieveAll().FirstOrDefault();

        //    parametros.ID = String.IsNullOrEmpty(parametros.ID) ? WrapperSession.ObtenerInstancia().Id : parametros.ID;
        //    parametros.Ano = String.IsNullOrEmpty(parametros.Ano) ? periodoActual.Ano : parametros.Ano;
        //    parametros.Termino = String.IsNullOrEmpty(parametros.Termino) ? periodoActual.Termino : parametros.Termino;

        //    switch (indiceReporte)
        //    {
        //        case "1":
        //            {
        //                args.Add("PROFESOR", parametros.ID);
        //                args.Add("ANO", parametros.Ano);
        //                args.Add("TERMINO", parametros.Termino);
        //                args.Add("ASIGNATURA", parametros.Asignatura);
        //                break;
        //            }
        //        case "2":
        //            {
        //                args.Add("PROFESOR", parametros.ID);
        //                args.Add("ANO", parametros.Ano);
        //                args.Add("TERMINO", parametros.Termino);
        //                args.Add("ASIGNATURA", parametros.Asignatura);
        //                break;
        //            }
        //        case "3":
        //            {
        //                args.Add("PROFESOR", parametros.ID);
        //                args.Add("ANO", parametros.Ano);
        //                args.Add("TERMINO", parametros.Termino);
        //                args.Add("ASIGNATURA", parametros.Asignatura); 
        //                break;
        //            }
        //        case "4":
        //            {
        //                args.Add("ID_NUM", parametros.ID);
        //                args.Add("PROGRAMA", parametros.Programa);
        //                break;
        //            }
        //        case "5":
        //            {
        //                args.Add("ID", parametros.ID);
        //                args.Add("PROGRAMA", parametros.Programa);
        //                break;
        //            }
        //        case "6":
        //            {
        //                args.Add("AREA", parametros.Area);
        //                args.Add("TERMINO", parametros.Termino);
        //                args.Add("AÑO", parametros.Ano);
        //                break;
        //            }
        //        case "7":
        //            {
        //                args.Add("AREA", parametros.Area);
        //                args.Add("TERMINO", parametros.Termino);
        //                args.Add("AÑO", parametros.Ano);
        //                break;
        //            }
        //        case "8":
        //            {
        //                args.Add("ID_NUM", parametros.ID);
        //                args.Add("Term", parametros.Termino);
        //                args.Add("Year", parametros.Ano);
        //                break;
        //            }
        //        case "9":
        //            {
        //                args.Add("ID_NUM", parametros.ID);
        //                args.Add("Term", parametros.Termino);
        //                args.Add("Year", parametros.Ano);
        //                break;
        //            }
        //        default: break;
        //    }

        //    return new { url = dataReporte.Direccion, parametros = args, titulo = dataReporte.Visualization };
        //}

        //private void GenerarReporte(string url, string fileName, Dictionary<string, string> param)
        //{
        //    string id = WrapperSession.ObtenerInstancia().Id;
        //    byte[] fileBytes = new MemoryLoader().LoadReport(url, FileFormat.Pdf, param);

        //    Response.Clear();
        //    Response.ContentType = "application/pdf";

        //    var header = "attachment; filename=\"" + fileName + "." + FileFormat.Pdf.ToString();

        //    Response.AddHeader("content-disposition", header);

        //    Response.BinaryWrite(fileBytes);
        //    Response.Flush();
        //    Response.End();
        //}
        //#endregion
    }
}

portalprofesores/WebUI/Views/Shared/_ContentHeader.cshtml
<div class="content-header">
	<div class="topbar">		
        <a href="#" class="uk-icon-cog uk-float-right"></a>
        <span class="uk-float-right">@(Model.Nombre + " " + Model.SegundoNombre + " " + Model.Apellido)</span>        
	</div>
	<div class="uk-width-1-1">
		<h1 class="section-title light-bottom-border">Selección de Asignaturas</h1>
		<div class="button_container">
			<button id="btnGuardar" onclick="save(@Model.ID)" class="button-square no-border uk-icon-save bg-green">Guardar</button>
			<button id="btnSalir" onclick="salir(@Model.ID)"class="button-square no-border uk-icon-trash-o bg-red">Cancelar</button>
		</div>
	</div>
</div>

portalprofesores/WebUI/Views/Shared/_ContentLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var dataReporte = WebUI.Helpers.WrapperReporte.GetInstance();
}

<div id="container" class="uk-grid">
	<nav class="uk-width-2-10 auto-height">
		<h1 class="section-title color-white uk-hidden-small">Opciones</h1>
		<ul class="menu uk-nav uk-nav-parent-icon">
			<li><a class="uk-icon-tasks" href="#"><span class="uk-hidden-small">Publicación de Calificaciones</span></a></li>
            <li><a class="uk-icon-share-square-o" href="#"><span class="uk-hidden-small">Auto-Evaluación</span></a></li>
			<li id="report-slider"><a class="uk-icon-bar-chart-o" href="#">
                <span class="uk-hidden-small">Reportes</span>
                <span class="uk-icon-chevron-down uk-float-right"></span>
            </a></li>            
            <ul id="report-data" style="display:none;">
                <li> <a class="uk-icon-users" href="@Url.Action("Index", "Reporte", new { r = "1" })">
                    <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("1").Visualization</span></a></li>
                <li> <a class="uk-icon-book" href="@Url.Action("Index", "Reporte", new { r = "2" })">
                    <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("2").Visualization</span></a></li>
                <li> <a class="uk-icon-book" href="@Url.Action("Index", "Reporte", new { r = "3" })">
                    <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("3").Visualization</span></a></li>

                @if (WebUI.Helpers.WrapperSession.ObtenerInstancia().TipoProfesor == "C")
                {
                    <li> <a class="uk-icon-book" href="@Url.Action("Index", "Reporte", new { r = "4" })">
                        <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("4").Visualization</span></a></li>
                    <li> <a class="uk-icon-book" href="@Url.Action("Index", "Reporte", new { r = "5" })">
                        <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("5").Visualization</span></a></li>
                    <li> <a class="uk-icon-book" href="@Url.Action("Index", "Reporte", new { r = "6" })">
                        <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("6").Visualization</span></a></li>
                    <li> <a class="uk-icon-book" href="@Url.Action("Index", "Reporte", new { r = "7" })">
                        <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("7").Visualization</span></a></li>
                    <li> <a class="uk-icon-book" href="@Url.Action("Index", "Reporte", new { r = "8" })">
                        <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("8").Visualization</span></a></li>
                    <li> <a class="uk-icon-book" href="@Url.Action("Index", "Reporte", new { r = "9" })">
                        <span class="uk-hidden-small">@dataReporte.ObtenerDataReporte("9").Visualization</span></a></li>
                }
            </ul>            
		</ul>
	</nav>
    <div id="content" class="uk-width-8-10 auto-height">
        @RenderSection("css", false)
        @RenderSection("scripts",false)
        @RenderBody()
    </div>
</div>

portalprofesores/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>

<!--[if lt IE 9]>
<link rel="stylesheet" href="@Url.Content("~/Content/ie.css")">
<![endif]-->
<!--[if IE 7]>
<link rel="stylesheet" href="@Url.Content("~/Content/ie7.css")">
<![endif]-->
<!--[if IE 6]>
<link rel="stylesheet" href="@Url.Content("~/Content/ie7.css")">
<![endif]-->
<noscript>
    <link rel="stylesheet" href="@Url.Content("~/Content/noscript.css")">
</noscript>
    <title>@ViewBag.Title</title>
	
    <meta http-equiv="X-UA-Compatible" content="IE=10">
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<link rel="stylesheet" href="@Url.Content("~/Content/uikit.min.css")">
	<link rel="stylesheet" href="@Url.Content("~/Content/style.css")">
	<script src="@Url.Content("~/Scripts/jquery-1.11.0.min.js")"></script>
	<script src="@Url.Content("~/Scripts/jquery-ui.min.js")"></script>
    <script src="@Url.Content("~/Scripts/uikit.min.js")"></script>
    <script src="@Url.Content("~/Scripts/ui.js")"></script>   
    <script src="@Url.Content("~/Scripts/Events.js")"></script>
</head>
<body>
	<header>
		<img class="logo" src="@Url.Content("~/Content/themes/base/images/logo_top.jpg")">
	</header>
    @RenderBody()
    <div class="loading">
        <span></span>
    </div>
</body>    
</html>


portalprofesores/WebUI/Views/Shared/_Topbar.cshtml
@{
    string id = WebUI.Helpers.WrapperSession.ObtenerInstancia().Id;
    int val = 0;
    int.TryParse(id, out val);
    var profesor = new DataAccess.ProfesorRepository().Find(val).NombreCompleto;    
}
<div class="topbar">		
    <div class="toogle-menu">
        <a href="#" class="top-icon uk-icon-cog uk-float-right"></a>
        <ul>
            <li class="uk-icon-lock"><a href="@Url.Action("Logout","Main")" class="black-font">Cerrar Sesión</a></li>
        </ul>
    </div>
    <span class="aligh-right color-white">@profesor</span>
</div>